### ISSUE TITLE
Missing example in README.md

### ISSUE THREAD

**Issue by TheE** [TheSmartnik/middleman-paginator#3]
The ReadMe promised an example, but does in fact not include one:
>Here is an example with bootstrap styles:
>
>```haml
>```

Could you maybe add one? It would help a lot when trying to use this gem.

**Comment by TheSmartnik** [comment]
@TheE thank you for opening an issue. Sorry for a long response.
It's probably too late for you, but let's hope. It will be useful for someone else 😄
